//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 04:44:06 PM EDT 
//


package com.freshdirect.fdstore.content.productfeed;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for nutritionInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="nutritionInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nutrition" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="nutritionType" use="required" type="{}LimitedString255" />
 *                 &lt;attribute name="uom" use="required" type="{}LimitedString50" />
 *                 &lt;attribute name="value" use="required" type="{}Decimal10-2" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nutritionInfo", propOrder = {
    "nutrition"
})
public class NutritionInfo {

    protected List<NutritionInfo.Nutrition> nutrition;

    /**
     * Gets the value of the nutrition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nutrition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNutrition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NutritionInfo.Nutrition }
     * 
     * 
     */
    public List<NutritionInfo.Nutrition> getNutrition() {
        if (nutrition == null) {
            nutrition = new ArrayList<NutritionInfo.Nutrition>();
        }
        return this.nutrition;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="nutritionType" use="required" type="{}LimitedString255" />
     *       &lt;attribute name="uom" use="required" type="{}LimitedString50" />
     *       &lt;attribute name="value" use="required" type="{}Decimal10-2" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Nutrition {

        @XmlAttribute(required = true)
        protected String nutritionType;
        @XmlAttribute(required = true)
        protected String uom;
        @XmlAttribute(required = true)
        protected BigDecimal value;

        /**
         * Gets the value of the nutritionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNutritionType() {
            return nutritionType;
        }

        /**
         * Sets the value of the nutritionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNutritionType(String value) {
            this.nutritionType = value;
        }

        /**
         * Gets the value of the uom property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUom() {
            return uom;
        }

        /**
         * Sets the value of the uom property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUom(String value) {
            this.uom = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValue(BigDecimal value) {
            this.value = value;
        }

    }

}
