//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 04:44:06 PM EDT 
//


package com.freshdirect.fdstore.content.productfeed;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.freshdirect.fdstore.content.productfeed package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.freshdirect.fdstore.content.productfeed
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ratings }
     * 
     */
    public Ratings createRatings() {
        return new Ratings();
    }

    /**
     * Create an instance of {@link SaleUnits.SaleUnit }
     * 
     */
    public SaleUnits.SaleUnit createSaleUnitsSaleUnit() {
        return new SaleUnits.SaleUnit();
    }

    /**
     * Create an instance of {@link GroupPrices }
     * 
     */
    public GroupPrices createGroupPrices() {
        return new GroupPrices();
    }

    /**
     * Create an instance of {@link SaleUnits }
     * 
     */
    public SaleUnits createSaleUnits() {
        return new SaleUnits();
    }

    /**
     * Create an instance of {@link Inventories }
     * 
     */
    public Inventories createInventories() {
        return new Inventories();
    }

    /**
     * Create an instance of {@link Products }
     * 
     */
    public Products createProducts() {
        return new Products();
    }

    /**
     * Create an instance of {@link NutritionInfo }
     * 
     */
    public NutritionInfo createNutritionInfo() {
        return new NutritionInfo();
    }

    /**
     * Create an instance of {@link Zone }
     * 
     */
    public Zone createZone() {
        return new Zone();
    }

    /**
     * Create an instance of {@link Images }
     * 
     */
    public Images createImages() {
        return new Images();
    }

    /**
     * Create an instance of {@link Products.Product }
     * 
     */
    public Products.Product createProductsProduct() {
        return new Products.Product();
    }

    /**
     * Create an instance of {@link Configurations.Configuration }
     * 
     */
    public Configurations.Configuration createConfigurationsConfiguration() {
        return new Configurations.Configuration();
    }

    /**
     * Create an instance of {@link Images.Image }
     * 
     */
    public Images.Image createImagesImage() {
        return new Images.Image();
    }

    /**
     * Create an instance of {@link Configurations.Configuration.VariationOption }
     * 
     */
    public Configurations.Configuration.VariationOption createConfigurationsConfigurationVariationOption() {
        return new Configurations.Configuration.VariationOption();
    }

    /**
     * Create an instance of {@link Inventories.Inventory }
     * 
     */
    public Inventories.Inventory createInventoriesInventory() {
        return new Inventories.Inventory();
    }

    /**
     * Create an instance of {@link GroupPrices.GroupPrice }
     * 
     */
    public GroupPrices.GroupPrice createGroupPricesGroupPrice() {
        return new GroupPrices.GroupPrice();
    }

    /**
     * Create an instance of {@link NutritionInfo.Nutrition }
     * 
     */
    public NutritionInfo.Nutrition createNutritionInfoNutrition() {
        return new NutritionInfo.Nutrition();
    }

    /**
     * Create an instance of {@link Prices.Price }
     * 
     */
    public Prices.Price createPricesPrice() {
        return new Prices.Price();
    }

    /**
     * Create an instance of {@link Attributes }
     * 
     */
    public Attributes createAttributes() {
        return new Attributes();
    }

    /**
     * Create an instance of {@link Ratings.Rating }
     * 
     */
    public Ratings.Rating createRatingsRating() {
        return new Ratings.Rating();
    }

    /**
     * Create an instance of {@link Configurations }
     * 
     */
    public Configurations createConfigurations() {
        return new Configurations();
    }

    /**
     * Create an instance of {@link Prices }
     * 
     */
    public Prices createPrices() {
        return new Prices();
    }

    /**
     * Create an instance of {@link Attributes.ProdAttribute }
     * 
     */
    public Attributes.ProdAttribute createAttributesProdAttribute() {
        return new Attributes.ProdAttribute();
    }

}
